apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nhkv-user-msi
spec:
  provider: azure
  secretObjects:
  - secretName: <secret_name> # Avoid sepcial characters in secret name
    type: Opaque
    data:
    - objectName: "<secret_name>"
      key: <secret_name>
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<client_id of key vault csi managed identity>"
    keyvaultName: "<key vault name>"
    objects: |
      array:
        - |
          objectName: mongodb-cs
          objectType: secret
          objectVersion: ""
    tenantId: "<Tenant_ID>"
