apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:latest
        command:
        - mongod
        - "--bind_ip_all"
        - "--replSet"
        - rs0
        - "--dbpath"
        - /data/mongofs
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: vol-azurefile-mongo
          mountPath: /data/mongofs
  volumeClaimTemplates:
  - metadata:
      name: vol-azurefile-mongo
    spec:
      storageClassName: sc-azurefile-mongo
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
